ktor:
    deployment:
        port: 8080
    application:
        modules:
            - yjh.ontongsal.SerializationKt.configureSerialization
            - yjh.ontongsal.ExposedKt.configureExposed
            - yjh.ontongsal.RoutingKt.configureRouting
